export const gtmEventNames = {
  appReady: 'appReady',
  pageViewEvent: 'pageViewEvent',
  homePageBannerClick: 'homePageBannerClick',
  homePageSearchButtonClick: 'homePageSearchButtonClick',
  homePageGemIconClick: 'homePageGemIconClick',
  homePageTrendingSectionItemClick: 'homePageTrendingSectionItemClick',
  homePageTrendingSectionViewMoreClick: 'homePageTrendingSectionViewMoreClick',
  homePageTurtlePickItemClick: 'homePageTurtlePickItemClick',
  homePageDynamicTagItemClick: 'homePageDynamicTagItemClick',
  homePageDynamicTagViewMoreClick: 'homePageDynamicTagViewMoreClick',
  homePageCategoryItemClick: 'homePageCategoryItemClick',
  homePageCategoryViewMoreClick: 'homePageCategoryViewMoreClick',
  homePageMerchantItemClick: 'homePageMerchantItemClick',
  homePageReadSectionItemClick: 'homePageReadSectionItemClick',
  homePagePlaygroundSectionItemClick: 'homePagePlaygroundSectionItemClick',
  homePageTodaysForageItemClick: 'homePageTodaysForageItemClick',
  homePageBottomHit: 'homePageBottomHit',
  homePageMenuHamburgerIconClick: 'homePageMenuHamburgerIconClick',
  tabIconClick: 'tabIconClick',
  menuItemClick: 'menuItemClick',
  menuItemUserProfilePictureClick: 'menuItemUserProfilePictureClick',
  likedItemsPageProductClick: 'likedItemsPageProductClick',
  ordersPageShopNowClick: 'ordersPageShopNowClick',
  communityPageArticleItemClick: 'communityPageArticleItemClick',
  communityPageBottomHit: 'communityPageBottomHit',
  marketPageSearchInputClick: 'marketPageSearchInputClick',
  marketPageBirdIconClick: 'marketPageBirdIconClick',
  marketPageSearchAgainNoResultButtonClick:
    'marketPageSearchAgainNoResultButtonClick',
  marketPageTrendingTagClick: 'marketPageTrendingTagClick',
  marketPageJustForYouClick: 'marketPageJustForYouClick',
  marketPageSortingDropdownClick: 'marketPageSortingDropdownClick',
  marketPageProductClick: 'marketPageProductClick',
  marketPageListExhausted: 'marketPageListExhausted',
  productDetailPageThumbnailClick: 'productDetailPageThumbnailClick',
  productDetailPageHomeIconClick: 'productDetailPageHomeIconClick',
  productDetailPageImageEnlarged: 'productDetailPageImageEnlarged',
  productDetailPageVideoPlayed: 'productDetailPageVideoPlayed',
  productDetailPageMerchantClick: 'productDetailPageMerchantClick',
  productDetailPageLikeIconClickWhenLoggedIn:
    'productDetailPageLikeIconClickWhenLoggedIn',
  productDetailPageLikeIconClickWhenNotLoggedIn:
    'productDetailPageLikeIconClickWhenNotLoggedIn',
  productDetailPageShareIconClick: 'productDetailPageShareIconClick',
  productDetailPageChatIconClick: 'productDetailPageChatIconClick',
  productDetailPageGoToCartIconClick: 'productDetailPageGoToCartIconClick',
  productDetailPageAddToCartClickWhenLoggedIn:
    'productDetailPageAddToCartClickWhenLoggedIn',
  productDetailPageAddToCartClickWhenNotLoggedIn:
    'productDetailPageAddToCartClickWhenNotLoggedIn',
  productDetailPageBuyNowClickWhenLoggedIn:
    'productDetailPageBuyNowClickWhenLoggedIn',
  productDetailPageBuyNowClickWhenNotLoggedIn:
    'productDetailPageBuyNowClickWhenNotLoggedIn',
  productDetailPageGemIconClick: 'productDetailPageGemIconClick',
  productDetailPageYouMayAlsoLikeItemClick:
    'productDetailPageYouMayAlsoLikeItemClick',
  filterPageCategoriesSectionClick: 'filterPageCategoriesSectionClick',
  filterPageCategoriesSectionItemClick: 'filterPageCategoriesSectionItemClick',
  filterPageMerchantsSectionClick: 'filterPageMerchantsSectionClick',
  filterPageMerchantSectionMerchantItemClick:
    'filterPageMerchantSectionMerchantItemClick',
  filterPageSpecialSectionClick: 'filterPageSpecialSectionClick',
  filterPageSpecialSectionTagItemClick: 'filterPageSpecialSectionTagItemClick',
  filterPageSearchBoxDropdownItemClick: 'filterPageSearchBoxDropdownItemClick',
  searchResultPageItemClick: 'searchResultPageItemClick',
  searchResultPageCartIconClick: 'searchResultPageCartIconClick',
  searchResultPageSearchIconClick: 'searchResultPageSearchIconClick',
  searchResultPageSearchTermResult: 'searchResultPageSearchTermResult',
  searchResultPageBottomHit: 'searchResultPageBottomHit',
  barteringHomeAddItemClick: 'barteringHomeAddItemClick',
  barteringHomeEditButtonClick: 'barteringHomeEditButtonClick',
  barteringHomePageOthersProductClick: 'barteringHomePageOthersProductClick',
  barteringHomePageOwnProductCircleClick:
    'barteringHomePageOwnProductCircleClick',
  allowNotificationPromptAccepted: 'allowNotificationPromptAccepted',
  allowNotificationPromptRejected: 'allowNotificationPromptRejected',
  notificationReceivedWhileAppOpen: 'notificationReceivedWhileAppOpen',
  notificationOpen: 'notificationOpen',
  profilePageClaimDailyGemClick: 'profilePageClaimDailyGemClick',
  profilePageCountryChanged: 'profilePageCountryChanged',
  profilePictureChanged: 'profilePictureChanged',
  profilePageShareGreenDayWithFriendsFor10000GemsClick:
    'profilePageShareGreenDayWithFriendsFor10000GemsClick',
  cartPageCheckoutButtonClick: 'cartPageCheckoutButtonClick',
  cartPageYouMayAlsoLikeItemClick: 'cartPageYouMayAlsoLikeItemClick',
  cartPageHeaderLikeIconClick: 'cartPageHeaderLikeIconClick',
  checkoutPageEnterPaymentDetailButtonClick:
    'checkoutPageEnterPaymentDetailButtonClick',
  checkoutPageGemApplyButtonClick: 'checkoutPageGemApplyButtonClick',
  checkoutPageVoucherApplyButtonClick: 'checkoutPageVoucherApplyButtonClick',
  checkoutPagePaymentCompleteButtonClick:
    'checkoutPagePaymentCompleteButtonClick',
  paymentCompleted: 'paymentCompleted',
  contactUsPageSendMessageButtonClick: 'contactUsPageSendMessageButtonClick',
  registerNewAccountClick: 'registerNewAccountClick',
};
